// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQqcSN9V6griL-15lrBJBGRFWVTqDCok',
    appId: '1:647173005180:web:ef21df379a40771df34ef9',
    messagingSenderId: '647173005180',
    projectId: 'my-twitter-clone-42e84',
    authDomain: 'my-twitter-clone-42e84.firebaseapp.com',
    storageBucket: 'my-twitter-clone-42e84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYLku6OSOQ6RZrRX6R8AhrPYaFrbowSsk',
    appId: '1:647173005180:android:2be1d27caba24817f34ef9',
    messagingSenderId: '647173005180',
    projectId: 'my-twitter-clone-42e84',
    storageBucket: 'my-twitter-clone-42e84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIxukhq5Zm7sEz4SPy08u3FRSrDZg_9yY',
    appId: '1:647173005180:ios:4391bd1bdf04bf60f34ef9',
    messagingSenderId: '647173005180',
    projectId: 'my-twitter-clone-42e84',
    storageBucket: 'my-twitter-clone-42e84.appspot.com',
    iosClientId: '647173005180-vd0g9kfiqbnq2e4r7k0mr9le8uduv9i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTwitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIxukhq5Zm7sEz4SPy08u3FRSrDZg_9yY',
    appId: '1:647173005180:ios:0abff92763100bc3f34ef9',
    messagingSenderId: '647173005180',
    projectId: 'my-twitter-clone-42e84',
    storageBucket: 'my-twitter-clone-42e84.appspot.com',
    iosClientId: '647173005180-9ajfjae3p9u32pfjb0r6k1q9qatkevs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTwitterClone.RunnerTests',
  );
}
